### PR TITLE
👌️ IMPROVE: Add tox.ini

### PR DESCRIPTION
**Pull request by najuzilu**
This PR adds `tox.ini` file

### CODE REVIEW

**Comment by najuzilu** [comment]
Failed attempt at using emojis in PR title...

**Comment by mmcky** [comment]
I am still learning `tox` myself -- looks nice.

**Comment by AakashGfude** [comment]
@najuzilu once you have updated the docs about how to run it locally, and happy with it. Will love to give this is a spin and see how it works :slightly_smiling_face:

**Comment by AakashGfude** [comment]
Hey @najuzilu did you get the same error at some point? is it path/env issue?
image

**Comment by najuzilu** [comment]
Not familiar with this error but I notice that you're using `myst-conda-env3`. I would suggest trying a new environment with `pip install -e .[rtd]` and trying again. Maybe that might fix it.

**Comment by AakashGfude** [comment]
@najuzilu tried that as well. still not working :(

**Comment by AakashGfude** [comment]
above error was tox `2.5.0` issue. apparently it does not work in that version. But that version is pretty old as well, so approving this.

**Review by AakashGfude — APPROVED** [review]

**Pull request merged**
