### PR TITLE
Support for assumption directive   #73

### PR DESCRIPTION
**Pull request by shailesh1729**
This patch provides support for the assumption directive. Code, as well as documentation, has been added for this directive. As described in issue #73, assumptions are frequently used and explicitly stated in the mathematical analysis of optimization algorithms.

### CODE REVIEW

**Comment by mmcky** [comment]
@AakashGfude can you please review this.

**Comment by AakashGfude** [comment]
Hi, @shailesh1729 @mmcky this looks good to me. We need to add a test and add a corresponding Assumption JSON file in translations. And then we should be good to merge. 
I am not too fused about the color choice, but @mmcky let us know If you have any opinions.

Sample:
Screen Shot 2022-07-12 at 6 52 37 pm

**Comment by mmcky** [comment]
> Appreciate the work on this PR @shailesh1729, let me know if you need help in writing test etc. The tests are failing here because of a separate issue, which we can resolve later.

thanks @AakashGfude and @shailesh1729. Is there a way we could add `colour` as an option to the `directive`? @AakashGfude are there any standard color definitions in the theme?

**Comment by AakashGfude** [comment]
> thanks @AakashGfude and @shailesh1729. Is there a way we could add `colour` as an option to the `directive`? @AakashGfude are there any standard color definitions in the theme?

@mmcky not at present. But we can add that as a feature in the future. 
We have certain colors defined as variables: 
```
  --note-title-color: rgba(68,138,255,.1);
  --note-border-color: #007bff;
  --warning-title-color: rgba(220,53,69,.1);
  --warning-border-color: #dc3545;
  --hint-title-color: rgba(255,193,7,.2);
  --hint-border-color: #ffc107;
  --caution-title-color: rgba(253,126,20,.1);
  --caution-border-color: #fd7e14;
  --grey-title-color: rgba(204,204,204,.2);
  --grey-border-color: #ccc;
```

which we keep using between the directives, but don't have any defined spec as such.

**Comment by AakashGfude** [comment]
@mmcky have merged master to this. And I think this is good to go apart from deciding on the color scheme. We can add translations to this in a later PR.

**Comment by shailesh1729** [comment]
@AakashGfude, thanks for your kind review. I have added an `Assumption.json` file in `translations/jsons` directory.  However, I am not sure how I need to add a test for the same. It looks like the `test_convert` function in `test_locale_convert` automatically adds test for each file. 

I couldn't figure out the correct translation of "assumption" in other languages.   Google translate seemed to suggest words based on hypothesis or supposition in French/Spanish.  So I have kept the English one only in the JSON file.

**Comment by shailesh1729** [comment]
Is there a plan to support a generic numbered directive where the actual name and color of the directive can be user controlled? In LateX one can create new theorem environments with whatever name one chooses. I keep thinking of a few more directive types like "fact", "hypothesis", "exercise" "challenge", etc.. Some directives are too specific to a particular domain [e.g. "constraint qualification" which is specific for Lagrangian duality].

**Comment by AakashGfude** [comment]
> Is there a plan to support a generic numbered directive where the actual name and color of the directive can be user controlled? In LateX one can create new theorem environments with whatever name one chooses. I keep thinking of a few more directive types like "fact", "hypothesis", "exercise" "challenge", etc. Some directives are too specific to a particular domain [e.g. "constraint qualification" which is specific for Lagrangian duality].

This can be a good feature. Thanks for bringing this up. I think we should create an issue regarding this in this repo. Would you mind creating one? Then we can plan it in one of our development cycles.

**Review by AakashGfude — APPROVED** [review]

**Comment by AakashGfude** [comment]
Thanks, heaps @shailesh1729 for this PR.  I think it's good to merge as is. We can discuss color schemes etc in issues and later PRs.

**Pull request merged**
